spring:
  cloud:
    config:
      discovery:
        enabled: false
      server:
        native:
          search-locations: file:/root/jt_prop/config
        git:
          uri: https://github.com/daweifly1/SpringcloudConfig/
          searchPaths: respo
          label: master
          username: tigerwer@126.com
          password: wangyidan1
#          //@git.password@
        peer2:
          search-locations: file:/root/jt_prop/config
        peer3:
          search-locations: file:/root/jt_prop/config
        prefix: /config
