spring:
  application:
    name: EUREKA

eureka:
  instance:
    appname: ${spring.application.name}
    #     prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
  server:
    enable-self-preservation: true
    #5秒清理一次
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: true
    #    fetch-registry: true
    service-url:
      defaultZone: ${k8s.defaultZone}
