eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:18001/eureka/,http://peer2:18002/eureka/
  server:
    renewal-percent-threshold: 0.5
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 20000
    response-cache-update-interval-ms: 20000
  instance:
    hostname: peer3
    prefer-ip-address: true
    health-check-url: http://${eureka.instance.hostname}:${server.port}${management.context-path}/health
  dashboard:
    path: /euadmin
