spring:
  cloud:
    config:
      discovery:
        enabled: false
      server:
        native:
          search-locations: file:/root/jt_prop/config
        git:
          uri: @git.uri@
          searchPaths: respo
          label: master
          username: @git.username@
          password: @git.password@
        prefix: /config
