spring:
  application:
    name: eureka-server
  profiles:
    active: peer1
  jackson:
    serialization:
      indent_output: false
  cloud:
    config:
      server:
        prefix: /config
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    renewal-percent-threshold: 0.49
    eviction-interval-timer-in-ms: 10000
    response-cache-update-interval-ms: 10000
    enable-self-preservation: false

---
spring:
  profiles: peer1
server:
  port: 7001
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/

---
spring:
  profiles: peer2
server:
  port: 7002
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/